### ISSUE TITLE
How to add attachments

### ISSUE THREAD

**Issue by user8446** [natescherer/PoshEmail#1]
Hello,

I didn't see anywhere in the docs how to add attachments. Is this supported?

**Comment by natescherer** [comment]
Sorry for the delay in response! Yes, Send-HtmlMailMessage supports everything that Send-MailMessage does, including attachments.

See the -Attachments param here: https://github.com/natescherer/PoshEmail/blob/master/docs/Send-HtmlMailMessage.md
